apps/ping: Fix build error if !LWIP_IPV6
Fix below build error if !LWIP_IPV6:

../../../apps/ping/ping.c: In function ‘ping_send’:
../../../apps/ping/ping.c:134:25: error: implicit declaration of function ‘ip6_addr_isipv6mappedipv4’ [-Werror=implicit-function-declaration]
   if(IP_IS_V6(addr) && !ip6_addr_isipv6mappedipv4(ip_2_ip6(addr))) {
                         ^~~~~~~~~~~~~~~~~~~~~~~~~
../../../apps/ping/ping.c:134:3: error: nested extern declaration of ‘ip6_addr_isipv6mappedipv4’ [-Werror=nested-externs]
   if(IP_IS_V6(addr) && !ip6_addr_isipv6mappedipv4(ip_2_ip6(addr))) {
   ^~
../../../apps/ping/ping.c:134:51: error: implicit declaration of function ‘ip_2_ip6’ [-Werror=implicit-function-declaration]
   if(IP_IS_V6(addr) && !ip6_addr_isipv6mappedipv4(ip_2_ip6(addr))) {
                                                   ^~~~~~~~
../../../apps/ping/ping.c:134:3: error: nested extern declaration of ‘ip_2_ip6’ [-Werror=nested-externs]
   if(IP_IS_V6(addr) && !ip6_addr_isipv6mappedipv4(ip_2_ip6(addr))) {
   ^~
cc1: all warnings being treated as errors

Fixes: 8ea25831dd7c ("simhost: remove ping implementation and use ping app instead")
Signed-off-by: Axel Lin <axel.lin@ingics.com>